FROM node:22-alpine

RUN apk add --no-cache wget

WORKDIR /app

ENV ASTRO_TELEMETRY_DISABLED=1
ENV NPM_CONFIG_FUND=false \
    NPM_CONFIG_AUDIT=false \
    NPM_CONFIG_UPDATE_NOTIFIER=false \
    NO_UPDATE_NOTIFIER=1

CMD sh -lc "npm install --no-fund --no-audit && npm run dev"
